WIDTH = 960
HEIGHT = 540
FPS = 60

PLAYER_SPEED = 5
PLAYER_MAX_LIFE = 3
PLAYER_MAX_BONUS_LIFE = 1
PLAYER_SHOOT_COOLDOWN = 15
PLAYER_RAPID_COOLDOWN = 5

BULLET_SPEED = 10
LASER_BULLET_SPEED_BONUS = 3
ENEMY_BULLET_SPEED = 6

ENEMY_SPEED = 3
ENEMY_SPAWN_DELAY = 60
ENEMY_SHOOT_DELAY = 50

POWERUP_SPEED = 3
POWERUP_DURATION = 8 * FPS

EXPLOSION_MAX_AGE = 25

POWER_NAMES = {
    "triple": "Triple tir",
    "rapid": "Tir rapide",
    "laser": "Laser",
}
