WIDTH = 960
HEIGHT = 540
FPS = 60

MUSIC_VOLUME = 0.35
SOUND_VOLUME = 0.55

PLAYER_SPEED = 5
PLAYER_MAX_LIFE = 3
PLAYER_MAX_BONUS_LIFE = 1
PLAYER_SHOOT_COOLDOWN = 15
PLAYER_RAPID_COOLDOWN = 5

BULLET_SPEED = 10
LASER_BULLET_SPEED_BONUS = 3
ENEMY_BULLET_SPEED = 6

ENEMY_SPEED = 3
ENEMY_SPAWN_DELAY = 60
ENEMY_SHOOT_DELAY = 50
ENEMY_MAX_SPAWN_COUNT = 6

BOSS_SPEED = 2
BOSS_X = WIDTH - 130
BOSS_SCORE_STEP = 50
BOSS_LIFE_STEP = 5
BOSS_SCORE_REWARD = 10
BOSS_CONTACT_COOLDOWN = FPS
BOSS_ATTACK_DELAY = 120
BOSS_BOMB_SPEED = 4
BOSS_BOMB_FUSE = 90
BOSS_FRAGMENT_BOMB_FUSE = 70
BOSS_BOMB_RADIUS = 48
BOSS_SMALL_BOMB_RADIUS = 34
BOSS_BOMB_EXPLOSION_AGE = 18
BOSS_LASER_DAMAGE = 3

POWERUP_SPEED = 3
POWERUP_DURATION = 8 * FPS

EXPLOSION_MAX_AGE = 25

BACKGROUND_SCORE_STEP = 100

POWER_NAMES = {
    "triple": "Triple tir",
    "rapid": "Tir rapide",
    "laser": "Laser",
}
