sonar.projectKey=DaTeVo_starship
sonar.organization=datevo
sonar.host.url=https://sonarcloud.io

sonar.sources=game
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
